# Generated by Django 4.0.6 on 2022-09-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0020_studetcourse_description_studetcourse_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='normalPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timingPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('asDate', models.DateField(null=True)),
                ('toDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timingPackageCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('packageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.timingpackage')),
            ],
        ),
        migrations.CreateModel(
            name='studentPackageDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('max_count', models.IntegerField(blank=True, null=True)),
                ('packageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.studentpackage')),
            ],
        ),
        migrations.CreateModel(
            name='studentPackageCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('packageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.studentpackage')),
            ],
        ),
        migrations.CreateModel(
            name='normalPackageCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('packageID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.normalpackage')),
            ],
        ),
    ]
