# Generated by Django 4.0.6 on 2022-09-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_user_phone'),
        ('package', '0002_remove_studentpackage_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpackage',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student'),
        ),
    ]
