# Generated by Django 4.1 on 2022-08-21 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courseDEP", "0001_initial"),
        ("authen", "0004_student_department_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "picture1",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_pictures/"
                    ),
                ),
                (
                    "picture2",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_pictures/"
                    ),
                ),
                ("price1", models.IntegerField(blank=True, null=True)),
                ("price2", models.IntegerField(blank=True, null=True)),
                ("returnPercent", models.IntegerField(blank=True, null=True)),
                ("day", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("startTime", models.DateField(null=True)),
                ("showforstudents", models.BooleanField(default=True, null=True)),
                ("showforTeacher", models.BooleanField(default=True, null=True)),
                ("enableforbuy", models.BooleanField(default=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("end", models.BooleanField(default=True, null=True)),
                ("endDateTime", models.DateField(null=True)),
                ("active", models.BooleanField(default=True, null=True)),
                (
                    "courseTypeID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseDEP.coursetype",
                    ),
                ),
                (
                    "departmentID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseDEP.department",
                    ),
                ),
                (
                    "gradeID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseDEP.grade",
                    ),
                ),
                (
                    "lessonID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseDEP.lessons",
                    ),
                ),
                (
                    "teacherID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Teacher",
                        to="authen.teacher",
                    ),
                ),
                (
                    "userID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="User",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yearID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courseDEP.year",
                    ),
                ),
            ],
        ),
    ]
