# Generated by Django 4.1 on 2022-08-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_coursehomework"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursehomework",
            name="fileCourse",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
