# Generated by Django 4.1 on 2022-08-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_remove_discountcourse_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="discountcourse", name="courseID",),
        migrations.RemoveField(model_name="discountcourse", name="discountID",),
        migrations.AddField(
            model_name="discountcourse",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="asDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="isPercent",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="reated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="toDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="discountcourse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
