# Generated by Django 4.0.6 on 2022-08-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_discountcourse_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveofflineheader',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='discountcourse',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='discountcourse',
            name='discountID',
        ),
        migrations.DeleteModel(
            name='ArchiveFiles',
        ),
        migrations.DeleteModel(
            name='ArchiveOfflineHeader',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='DiscountCourse',
        ),
    ]
