# Generated by Django 4.0.6 on 2022-09-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_user_phone'),
        ('course', '0018_alter_coursehomework_filecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studetcourse',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studetcourse',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='studetcourse',
            name='price',
        ),
        migrations.CreateModel(
            name='BlocedStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('courseID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student')),
            ],
        ),
    ]
