# Generated by Django 4.0.6 on 2022-09-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_remove_studetcourse_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studetcourse',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studetcourse',
            name='enable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='studetcourse',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
