# Generated by Django 4.0.6 on 2022-09-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_alter_student_address_alter_student_parentname_and_more'),
        ('course', '0020_studetcourse_description_studetcourse_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseHWansView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Homeworkanswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='hw_answer/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('courseHWID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursehomework')),
                ('studentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student')),
            ],
        ),
    ]
