# Generated by Django 4.0.6 on 2022-09-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_coursehwansview_homeworkanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseHWansView',
        ),
        migrations.RenameField(
            model_name='homeworkanswer',
            old_name='studentId',
            new_name='studentID',
        ),
    ]
