# Generated by Django 4.0.6 on 2022-09-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_delete_coursehwansview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
