# Generated by Django 4.0.6 on 2022-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_quiz',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
