# Generated by Django 4.0.6 on 2022-08-23 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_remove_archiveofflineheader_courseid_and_more'),
        ('authen', '0007_alter_user_phone'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizheader',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='course.course'),
        ),
        migrations.AlterField(
            model_name='quizheader',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.teacher'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizheader'),
        ),
        migrations.AlterField(
            model_name='studentqueez',
            name='quizQuestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizquestion'),
        ),
    ]
