# Generated by Django 4.0.6 on 2022-09-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizheader_course_alter_quizheader_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizheader',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizheader',
            name='start_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
