# Generated by Django 4.0.6 on 2022-09-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizheader_end_data_quizheader_start_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizheader',
            name='min_range',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
