# Generated by Django 4.0.6 on 2022-09-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_user_phone'),
        ('quiz', '0005_quizheader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentqueez',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student'),
        ),
    ]
