# Generated by Django 4.0.6 on 2022-09-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_user_phone'),
        ('quiz', '0006_studentqueez_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalquizHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('quizTime', models.IntegerField(blank=True, default=0, null=True)),
                ('question_count', models.IntegerField(blank=True, default=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='totalquizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=350, null=True)),
                ('answer1', models.TextField(blank=True, max_length=400, null=True)),
                ('answer2', models.TextField(blank=True, max_length=400, null=True)),
                ('answer3', models.TextField(blank=True, max_length=400, null=True)),
                ('answer4', models.TextField(blank=True, max_length=400, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.totalquizheader')),
            ],
        ),
        migrations.CreateModel(
            name='totalstudentQueez',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('quizQuestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.totalquizquestion')),
                ('quizheader', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.totalquizheader')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student')),
            ],
        ),
        migrations.CreateModel(
            name='totalquizSubjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quizheader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.totalquizheader')),
            ],
        ),
        migrations.AddField(
            model_name='totalquizquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.totalquizsubjects'),
        ),
    ]
