# Generated by Django 4.0.6 on 2022-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_totalquizheader_totalquizquestion_totalstudentqueez_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalquizheader',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalquizheader',
            name='start_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
