# Generated by Django 4.0.6 on 2022-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_totalquizheader_end_data_totalquizheader_start_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='header_id',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='title',
        ),
        migrations.RemoveField(
            model_name='totalquizquestion',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='totalquizquestion',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='totalquizquestion',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='totalquizquestion',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='totalquizquestion',
            name='title',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='has_negative',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question',
            field=models.ImageField(blank=True, null=True, upload_to='q_question/'),
        ),
        migrations.AddField(
            model_name='totalquizquestion',
            name='has_negative',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='totalquizquestion',
            name='question',
            field=models.ImageField(blank=True, null=True, upload_to='q_question/'),
        ),
    ]
