# Generated by Django 4.0.6 on 2022-09-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumdetail',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forum_file/'),
        ),
        migrations.AlterField(
            model_name='forumdetail',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumheader',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='forumheader',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
