# Generated by Django 4.0.6 on 2022-09-03 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_forumdetail_created_at_alter_forumdetail_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumdetail',
            name='student',
        ),
        migrations.RemoveField(
            model_name='forumdetail',
            name='teacher',
        ),
        migrations.AddField(
            model_name='forumdetail',
            name='Userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
