# Generated by Django 4.0.6 on 2022-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_alter_student_managers_alter_teacher_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addres',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
