# Generated by Django 4.0.6 on 2022-08-22 22:17

import authen.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_student_department_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver', models.IntegerField()),
                ('password', models.CharField(default=authen.models.generate_otp, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
