# Generated by Django 4.0.6 on 2022-08-22 22:35

import authen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=authen.models.generate_otp, max_length=7),
        ),
    ]
