# Generated by Django 4.0.6 on 2022-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0010_alter_user_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parentNationalCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
