# Generated by Django 4.0.6 on 2022-09-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_alter_student_parentnationalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='receiver',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
