# Generated by Django 4.0.6 on 2022-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0013_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=128, verbose_name='password'),
        ),
    ]
