# Generated by Django 4.0.6 on 2022-09-05 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student')),
            ],
        ),
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('normal', 'normal'), ('timing', 'timing'), ('student', 'student'), ('course', 'course')], max_length=50, null=True)),
                ('buyID', models.IntegerField(blank=True, null=True)),
                ('studentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.student')),
            ],
        ),
    ]
