# Generated by Django 4.1 on 2022-08-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="picture",
            field=models.ImageField(null=True, upload_to="banner/"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="picture",
            field=models.ImageField(null=True, upload_to="slider/"),
        ),
    ]
