# Generated by Django 4.0.6 on 2022-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
