# Generated by Django 4.0.6 on 2022-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_buy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
