# Generated by Django 4.0.6 on 2022-09-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefiles',
            name='fileArchibe',
            field=models.FileField(blank=True, null=True, upload_to='upload_course/'),
        ),
    ]
