# Generated by Django 4.0.6 on 2022-09-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_archivefiles_filearchibe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivefiles',
            name='fileArchibe',
        ),
        migrations.AddField(
            model_name='archivefiles',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
