# Generated by Django 4.0.6 on 2022-09-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_remove_archivefiles_filearchibe_archivefiles_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivefiles',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
