# Generated by Django 4.0.6 on 2022-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_rename_reated_at_archivefiles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefiles',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archivefiles',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='archiveofflineheader',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
